@TmsApi_HostAddress = http://localhost:5079

# GET {{TmsApi_HostAddress}}/weatherforecast/
# Accept: application/json

###

# Without Header:  401 Unauthorized
# GET {{TmsApi_HostAddress}}/api/assessments/results/
# Accept: application/json


# With Header:  HTTP/1.1 200 OK,  with JSON Data
GET {{TmsApi_HostAddress}}/api/assessments/results/
Accept: application/json
X-Training-User: Mesay
